#!/bin/zsh

# Run brew bundle dump
brew bundle dump --force

# Check if there are any changes to the Brewfile
if ! git diff --quiet Brewfile; then
    # Add the updated Brewfile to git staging
    git add Brewfile

    # Commit with a standard message
    git commit -m "Update Brewfile"

    # Push the changes
    git push
fi
