# These are supported funding model platforms

github: ruchernchong
patreon: ruchernchong
open_collective: ruchernchong
ko_fi: ruchernchong
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
