# These are supported funding model platforms

github: ruchernchong
open_collective: 
ko_fi: 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
polar: ruchernchong
buy_me_a_coffee: 
thanks_dev: 
