tap "aws/tap"
tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "libsql/sqld"
tap "mongodb/brew"
tap "ngrok/ngrok"
tap "oven-sh/bun"
tap "pulumi/tap"
tap "sst/tap"
tap "stripe/stripe-cli"
tap "teamookla/speedtest"
tap "tursodatabase/tap"
brew "act"
brew "libtiff"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "aom"
brew "libssh2"
brew "sqlite"
brew "aria2"
brew "pycparser"
brew "cffi"
brew "cryptography"
brew "aws-sam-cli"
brew "bash"
brew "bash-completion"
brew "brew-cask-completion"
brew "cabextract"
brew "cdrtools"
brew "circleci"
brew "cli53"
brew "direnv"
brew "docker-compose"
brew "doctl"
brew "gh"
brew "openjpeg"
brew "ghostscript"
brew "git"
brew "unbound"
brew "netpbm"
brew "groff"
brew "libheif"
brew "imagemagick"
brew "jq"
brew "lima"
brew "lzip"
brew "node"
brew "mongosh"
brew "neonctl"
brew "nvm"
brew "ollama", restart_service: true
brew "opentofu"
brew "pnpm"
brew "postgresql@17", restart_service: true
brew "python@3.12"
brew "python-tk@3.12"
brew "qemu"
brew "tflint"
brew "tfsec"
brew "uv"
brew "wimlib"
brew "yarn"
brew "mongodb/brew/mongodb-community"
brew "oven-sh/bun/bun"
brew "pulumi/tap/pulumi"
brew "sst/tap/sst"
brew "stripe/stripe-cli/stripe"
brew "teamookla/speedtest/speedtest"
brew "tursodatabase/tap/turso"
cask "1password-cli"
cask "google-cloud-sdk"
cask "ngrok"
mas "1Password for Safari", id: 1569813296
mas "Ahrefs SEO Toolbar", id: 6499265972
mas "Command X", id: 6448461551
mas "Dato", id: 1470584107
mas "Gifski", id: 1351639930
mas "HEIC Converter", id: 1294126402
mas "iMovie", id: 408981434
mas "JSONPeep", id: 1458969831
mas "Keynote", id: 409183694
mas "moomoo", id: 1482713641
mas "NextDNS", id: 1464122853
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Sink It for Reddit", id: 6449873635
mas "Telegram", id: 747648890
mas "TestFlight", id: 899247664
mas "WireGuard", id: 1451685025
vscode "aaron-bond.better-comments"
vscode "astro-build.astro-vscode"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.npm-intellisense"
vscode "continue.continue"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "firefox-devtools.vscode-firefox-debug"
vscode "formulahendry.auto-close-tag"
vscode "foxundermoon.shell-format"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-syntax"
vscode "icrawl.discord-vscode"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-ossdata.vscode-postgresql"
vscode "ms-playwright.playwright"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.github-issues-prs"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vscode.vscode-typescript-next"
vscode "msjsdiag.vscode-react-native"
vscode "pulumi.pulumi-lsp-client"
vscode "redhat.vscode-yaml"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "wix.vscode-import-cost"
